export { default as ParticleViewer } from './ParticleViewer'
export { sampleShape, SHAPE_NAMES } from './shapes'
export type { ShapeName, ShapeData } from './shapes'
export { heroParticleConfig, sectionParticles, COSMIC_COLORS } from './particles.config'
export type { SectionParticleConfig } from './particles.config'